#!/usr/bin/env python3

# -*- coding: utf-8 -*-

import os
import sys

from sphinx.ext.autodoc import between

sys.path.insert(0, os.path.abspath('../../pymimic_dev'))


# -- General configuration ------------------------------------------------

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.mathjax',
    'sphinx.ext.githubpages',
    'sphinx.ext.viewcode',
    'numpydoc',
    'sphinx.ext.napoleon',
]

# Paths containing templates, relative to this directory.
templates_path = ['_templates']

# Source suffix
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'pymimic'
copyright = '2018, Amery Gration'
author = 'Amery Gration'

# Version info (short X.Y version).
version = '0.0.0'

# Version info (full version, including alpha/beta/rc tags).
release = '0.0.0'

# Language for content autogenerated by Sphinx.
language = None

# Directories to ignore when looking for source files.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# Name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# Ignore `todo` and `todoList`.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# Theme to use for HTML and HTML Help pages.
html_theme = 'sphinx_rtd_theme'#'alabaster'

# Paths that containing custom static files.
html_static_path = ['_static']


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'pymimicdoc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# List of tuple for grouping the document tree into LaTeX files.
latex_documents = [
    (master_doc, 'pymimic.tex', 'pymimic Documentation',
     'Amery Gration', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# List of tuples for manual page.
man_pages = [
    (master_doc, 'pymimic', 'pymimic Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# List of tuple for grouping the document tree into Texinfo files.
texinfo_documents = [
    (master_doc, 'pymimic', 'pymimic Documentation',
     author, 'pymimic', 'One line description of project.',
     'Miscellaneous'),
]
